export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: "MARK_NOTIFICATION_AS_READ_BY_ID",
    MARK_ALL_NOTIFICATION_AS_READ:"MARK_ALL_NOTIFICATION_AS_READ",
    START_MARK_AS_READ:"START_MARK_AS_READ",
    FINISH_MARK_AS_READ:"FINISH_MARK_AS_READ",
    START_LOGIN:"START_LOGIN",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED"
}
